//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsuntosMigratoriosService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class SolicitudInfo : object
    {
        
        private string ContraseniaWsField;
        
        private string CorreoElectronicoField;
        
        private string DireccionResidenciaField;
        
        private int ExoneracionField;
        
        private System.DateTime FechaCaducidadDocumentoField;
        
        private System.DateTime FechaEmisionDocumentoField;
        
        private System.DateTime FechaFacturaField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.DateTime FechaPagoField;
        
        private System.DateTime FechaRegistroSolicitudField;
        
        private byte[] FotoField;
        
        private int IdActividadVisaField;
        
        private int IdActoConsularSolicitudVisaField;
        
        private int IdActoConsularVisaField;
        
        private int IdCalidadMigratoriaField;
        
        private int IdCentroAdministrativoField;
        
        private int IdCiudadNacimientoField;
        
        private int IdCiudadResidenciaField;
        
        private int IdEntidadAuspicianteField;
        
        private int IdFormaPagoField;
        
        private int IdFuncionarioCajeroField;
        
        private int IdFuncionarioCreacionEsigexField;
        
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        private int IdGrupoVisaField;
        
        private int IdNacionalidadField;
        
        private int IdTipoDocumentoField;
        
        private System.Guid IdTramiteNuevoSistemaField;
        
        private int LugarEmisionDocumentoField;
        
        private string NombresExtranjeroField;
        
        private string NumeroComprobanteField;
        
        private string NumeroDocumentoField;
        
        private string NumeroFacturaField;
        
        private string NumeroVisaNuevoSistemaField;
        
        private string ObservacionSolicitudField;
        
        private string PrimerApellidoExtranjeroField;
        
        private AsuntosMigratoriosService.RequisitosSolicitudMessage[] RequisitosVisaField;
        
        private string SegundoApellidoExtranjeroField;
        
        private string TelefonoField;
        
        private string UsuarioWsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs
        {
            get
            {
                return this.ContraseniaWsField;
            }
            set
            {
                this.ContraseniaWsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionResidencia
        {
            get
            {
                return this.DireccionResidenciaField;
            }
            set
            {
                this.DireccionResidenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Exoneracion
        {
            get
            {
                return this.ExoneracionField;
            }
            set
            {
                this.ExoneracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCaducidadDocumento
        {
            get
            {
                return this.FechaCaducidadDocumentoField;
            }
            set
            {
                this.FechaCaducidadDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmisionDocumento
        {
            get
            {
                return this.FechaEmisionDocumentoField;
            }
            set
            {
                this.FechaEmisionDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura
        {
            get
            {
                return this.FechaFacturaField;
            }
            set
            {
                this.FechaFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroSolicitud
        {
            get
            {
                return this.FechaRegistroSolicitudField;
            }
            set
            {
                this.FechaRegistroSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActividadVisa
        {
            get
            {
                return this.IdActividadVisaField;
            }
            set
            {
                this.IdActividadVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularSolicitudVisa
        {
            get
            {
                return this.IdActoConsularSolicitudVisaField;
            }
            set
            {
                this.IdActoConsularSolicitudVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularVisa
        {
            get
            {
                return this.IdActoConsularVisaField;
            }
            set
            {
                this.IdActoConsularVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCalidadMigratoria
        {
            get
            {
                return this.IdCalidadMigratoriaField;
            }
            set
            {
                this.IdCalidadMigratoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativo
        {
            get
            {
                return this.IdCentroAdministrativoField;
            }
            set
            {
                this.IdCentroAdministrativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudadNacimiento
        {
            get
            {
                return this.IdCiudadNacimientoField;
            }
            set
            {
                this.IdCiudadNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudadResidencia
        {
            get
            {
                return this.IdCiudadResidenciaField;
            }
            set
            {
                this.IdCiudadResidenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntidadAuspiciante
        {
            get
            {
                return this.IdEntidadAuspicianteField;
            }
            set
            {
                this.IdEntidadAuspicianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago
        {
            get
            {
                return this.IdFormaPagoField;
            }
            set
            {
                this.IdFormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero
        {
            get
            {
                return this.IdFuncionarioCajeroField;
            }
            set
            {
                this.IdFuncionarioCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCreacionEsigex
        {
            get
            {
                return this.IdFuncionarioCreacionEsigexField;
            }
            set
            {
                this.IdFuncionarioCreacionEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema
        {
            get
            {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set
            {
                this.IdFuncionarioNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupoVisa
        {
            get
            {
                return this.IdGrupoVisaField;
            }
            set
            {
                this.IdGrupoVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNacionalidad
        {
            get
            {
                return this.IdNacionalidadField;
            }
            set
            {
                this.IdNacionalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento
        {
            get
            {
                return this.IdTipoDocumentoField;
            }
            set
            {
                this.IdTipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema
        {
            get
            {
                return this.IdTramiteNuevoSistemaField;
            }
            set
            {
                this.IdTramiteNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LugarEmisionDocumento
        {
            get
            {
                return this.LugarEmisionDocumentoField;
            }
            set
            {
                this.LugarEmisionDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresExtranjero
        {
            get
            {
                return this.NombresExtranjeroField;
            }
            set
            {
                this.NombresExtranjeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante
        {
            get
            {
                return this.NumeroComprobanteField;
            }
            set
            {
                this.NumeroComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaNuevoSistema
        {
            get
            {
                return this.NumeroVisaNuevoSistemaField;
            }
            set
            {
                this.NumeroVisaNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionSolicitud
        {
            get
            {
                return this.ObservacionSolicitudField;
            }
            set
            {
                this.ObservacionSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellidoExtranjero
        {
            get
            {
                return this.PrimerApellidoExtranjeroField;
            }
            set
            {
                this.PrimerApellidoExtranjeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AsuntosMigratoriosService.RequisitosSolicitudMessage[] RequisitosVisa
        {
            get
            {
                return this.RequisitosVisaField;
            }
            set
            {
                this.RequisitosVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellidoExtranjero
        {
            get
            {
                return this.SegundoApellidoExtranjeroField;
            }
            set
            {
                this.SegundoApellidoExtranjeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs
        {
            get
            {
                return this.UsuarioWsField;
            }
            set
            {
                this.UsuarioWsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequisitosSolicitudMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class RequisitosSolicitudMessage : object
    {
        
        private int IdActoConsularVisaField;
        
        private int IdRequisitoField;
        
        private string ObservacionField;
        
        private bool SeleccionadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularVisa
        {
            get
            {
                return this.IdActoConsularVisaField;
            }
            set
            {
                this.IdActoConsularVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRequisito
        {
            get
            {
                return this.IdRequisitoField;
            }
            set
            {
                this.IdRequisitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion
        {
            get
            {
                return this.ObservacionField;
            }
            set
            {
                this.ObservacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seleccionado
        {
            get
            {
                return this.SeleccionadoField;
            }
            set
            {
                this.SeleccionadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AsuntosMigratoriosService.GeneracionVisaMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AsuntosMigratoriosService.OrdenCedulacionMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AsuntosMigratoriosService.GeneracionSolicitudMessage))]
    public partial class Resultado : object
    {
        
        private string CodigoField;
        
        private string CodigoDescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDescripcion
        {
            get
            {
                return this.CodigoDescripcionField;
            }
            set
            {
                this.CodigoDescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneracionVisaMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class GeneracionVisaMessage : AsuntosMigratoriosService.Resultado
    {
        
        private int IdTramiteVisaField;
        
        private string NumeroTramiteField;
        
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteVisa
        {
            get
            {
                return this.IdTramiteVisaField;
            }
            set
            {
                this.IdTramiteVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite
        {
            get
            {
                return this.NumeroTramiteField;
            }
            set
            {
                this.NumeroTramiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class OrdenCedulacionMessage : AsuntosMigratoriosService.Resultado
    {
        
        private string CodigoVerificacionField;
        
        private int IdTramiteOrdenCedulacionField;
        
        private string NumeroTramiteField;
        
        private int SecuencialActuacionField;
        
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoVerificacion
        {
            get
            {
                return this.CodigoVerificacionField;
            }
            set
            {
                this.CodigoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteOrdenCedulacion
        {
            get
            {
                return this.IdTramiteOrdenCedulacionField;
            }
            set
            {
                this.IdTramiteOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite
        {
            get
            {
                return this.NumeroTramiteField;
            }
            set
            {
                this.NumeroTramiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecuencialActuacion
        {
            get
            {
                return this.SecuencialActuacionField;
            }
            set
            {
                this.SecuencialActuacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneracionSolicitudMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class GeneracionSolicitudMessage : AsuntosMigratoriosService.Resultado
    {
        
        private int IdSecuencialActuacionField;
        
        private int IdTramiteSolicitudField;
        
        private string NumeroTramiteField;
        
        private string NumeroVisaEsigexField;
        
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSecuencialActuacion
        {
            get
            {
                return this.IdSecuencialActuacionField;
            }
            set
            {
                this.IdSecuencialActuacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteSolicitud
        {
            get
            {
                return this.IdTramiteSolicitudField;
            }
            set
            {
                this.IdTramiteSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite
        {
            get
            {
                return this.NumeroTramiteField;
            }
            set
            {
                this.NumeroTramiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaEsigex
        {
            get
            {
                return this.NumeroVisaEsigexField;
            }
            set
            {
                this.NumeroVisaEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisaInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class VisaInfo : object
    {
        
        private string ContraseniaWsField;
        
        private byte[] DocumentoPdfField;
        
        private int ExoneracionField;
        
        private System.DateTime FechaAutorizacionField;
        
        private System.DateTime FechaFacturaField;
        
        private System.DateTime FechaPagoField;
        
        private System.DateTime FechaVigenciaVisaField;
        
        private int IdFormaPagoField;
        
        private int IdFuncionarioCajeroField;
        
        private int IdFuncionarioEsigexAutorizacionField;
        
        private int IdFuncionarioEsigexVisaField;
        
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        private System.Guid IdTramiteNuevoSistemaField;
        
        private int IdTramiteSolicitudField;
        
        private string NumeroComprobanteField;
        
        private int NumeroEntradasPermitidasField;
        
        private string NumeroFacturaField;
        
        private string NumeroVisaNuevoSistemaField;
        
        private string ObservacionAutorizacionField;
        
        private string UsuarioWsField;
        
        private bool VisaAutorizadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs
        {
            get
            {
                return this.ContraseniaWsField;
            }
            set
            {
                this.ContraseniaWsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentoPdf
        {
            get
            {
                return this.DocumentoPdfField;
            }
            set
            {
                this.DocumentoPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Exoneracion
        {
            get
            {
                return this.ExoneracionField;
            }
            set
            {
                this.ExoneracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAutorizacion
        {
            get
            {
                return this.FechaAutorizacionField;
            }
            set
            {
                this.FechaAutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura
        {
            get
            {
                return this.FechaFacturaField;
            }
            set
            {
                this.FechaFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVigenciaVisa
        {
            get
            {
                return this.FechaVigenciaVisaField;
            }
            set
            {
                this.FechaVigenciaVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago
        {
            get
            {
                return this.IdFormaPagoField;
            }
            set
            {
                this.IdFormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero
        {
            get
            {
                return this.IdFuncionarioCajeroField;
            }
            set
            {
                this.IdFuncionarioCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioEsigexAutorizacion
        {
            get
            {
                return this.IdFuncionarioEsigexAutorizacionField;
            }
            set
            {
                this.IdFuncionarioEsigexAutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioEsigexVisa
        {
            get
            {
                return this.IdFuncionarioEsigexVisaField;
            }
            set
            {
                this.IdFuncionarioEsigexVisaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema
        {
            get
            {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set
            {
                this.IdFuncionarioNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema
        {
            get
            {
                return this.IdTramiteNuevoSistemaField;
            }
            set
            {
                this.IdTramiteNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteSolicitud
        {
            get
            {
                return this.IdTramiteSolicitudField;
            }
            set
            {
                this.IdTramiteSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante
        {
            get
            {
                return this.NumeroComprobanteField;
            }
            set
            {
                this.NumeroComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEntradasPermitidas
        {
            get
            {
                return this.NumeroEntradasPermitidasField;
            }
            set
            {
                this.NumeroEntradasPermitidasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaNuevoSistema
        {
            get
            {
                return this.NumeroVisaNuevoSistemaField;
            }
            set
            {
                this.NumeroVisaNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionAutorizacion
        {
            get
            {
                return this.ObservacionAutorizacionField;
            }
            set
            {
                this.ObservacionAutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs
        {
            get
            {
                return this.UsuarioWsField;
            }
            set
            {
                this.UsuarioWsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisaAutorizada
        {
            get
            {
                return this.VisaAutorizadaField;
            }
            set
            {
                this.VisaAutorizadaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class OrdenCedulacionInfo : object
    {
        
        private string ContraseniaWsField;
        
        private int DiasValidezField;
        
        private System.DateTime FechaFacturaField;
        
        private System.DateTime FechaFinValidezOrdenCedulacionField;
        
        private System.DateTime FechaInicioValidezOrdenCedulacionField;
        
        private System.DateTime FechaPagoField;
        
        private System.DateTime FechaRegistroOrdenCedulacionField;
        
        private int IdActoConsularOrdenCedulacionField;
        
        private int IdCentroAdministrativoOrdenCedulacionField;
        
        private int IdExoneracionField;
        
        private int IdFormaPagoField;
        
        private int IdFuncionarioCajeroField;
        
        private int IdFuncionarioCreacionEsigexField;
        
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        private int IdFuncionarioPagoEsigexField;
        
        private int IdFuncionarioSignatarioEsigexField;
        
        private System.Guid IdTramiteNuevoSistemaField;
        
        private int IdTramiteVisaEsigexField;
        
        private string NumeroComprobantePagoField;
        
        private string NumeroFacturaField;
        
        private string ObservacionOrdenCedulacionField;
        
        private string UsuarioWsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs
        {
            get
            {
                return this.ContraseniaWsField;
            }
            set
            {
                this.ContraseniaWsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasValidez
        {
            get
            {
                return this.DiasValidezField;
            }
            set
            {
                this.DiasValidezField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura
        {
            get
            {
                return this.FechaFacturaField;
            }
            set
            {
                this.FechaFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFinValidezOrdenCedulacion
        {
            get
            {
                return this.FechaFinValidezOrdenCedulacionField;
            }
            set
            {
                this.FechaFinValidezOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicioValidezOrdenCedulacion
        {
            get
            {
                return this.FechaInicioValidezOrdenCedulacionField;
            }
            set
            {
                this.FechaInicioValidezOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroOrdenCedulacion
        {
            get
            {
                return this.FechaRegistroOrdenCedulacionField;
            }
            set
            {
                this.FechaRegistroOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularOrdenCedulacion
        {
            get
            {
                return this.IdActoConsularOrdenCedulacionField;
            }
            set
            {
                this.IdActoConsularOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativoOrdenCedulacion
        {
            get
            {
                return this.IdCentroAdministrativoOrdenCedulacionField;
            }
            set
            {
                this.IdCentroAdministrativoOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdExoneracion
        {
            get
            {
                return this.IdExoneracionField;
            }
            set
            {
                this.IdExoneracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago
        {
            get
            {
                return this.IdFormaPagoField;
            }
            set
            {
                this.IdFormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero
        {
            get
            {
                return this.IdFuncionarioCajeroField;
            }
            set
            {
                this.IdFuncionarioCajeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCreacionEsigex
        {
            get
            {
                return this.IdFuncionarioCreacionEsigexField;
            }
            set
            {
                this.IdFuncionarioCreacionEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema
        {
            get
            {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set
            {
                this.IdFuncionarioNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioPagoEsigex
        {
            get
            {
                return this.IdFuncionarioPagoEsigexField;
            }
            set
            {
                this.IdFuncionarioPagoEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioSignatarioEsigex
        {
            get
            {
                return this.IdFuncionarioSignatarioEsigexField;
            }
            set
            {
                this.IdFuncionarioSignatarioEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema
        {
            get
            {
                return this.IdTramiteNuevoSistemaField;
            }
            set
            {
                this.IdTramiteNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteVisaEsigex
        {
            get
            {
                return this.IdTramiteVisaEsigexField;
            }
            set
            {
                this.IdTramiteVisaEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobantePago
        {
            get
            {
                return this.NumeroComprobantePagoField;
            }
            set
            {
                this.NumeroComprobantePagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionOrdenCedulacion
        {
            get
            {
                return this.ObservacionOrdenCedulacionField;
            }
            set
            {
                this.ObservacionOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs
        {
            get
            {
                return this.UsuarioWsField;
            }
            set
            {
                this.UsuarioWsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionV2Info", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    public partial class OrdenCedulacionV2Info : object
    {
        
        private string ContraseniaWsField;
        
        private byte[] DocumentoPdfField;
        
        private System.DateTime FechaRegistroOrdenCedulacionField;
        
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        private int IdFuncionarioOrdenCedulacionEsigexField;
        
        private System.Guid IdTramiteNuevoSistemaField;
        
        private int IdTramiteOrdenCedulacionEsigexField;
        
        private string UsuarioWsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs
        {
            get
            {
                return this.ContraseniaWsField;
            }
            set
            {
                this.ContraseniaWsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentoPdf
        {
            get
            {
                return this.DocumentoPdfField;
            }
            set
            {
                this.DocumentoPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroOrdenCedulacion
        {
            get
            {
                return this.FechaRegistroOrdenCedulacionField;
            }
            set
            {
                this.FechaRegistroOrdenCedulacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema
        {
            get
            {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set
            {
                this.IdFuncionarioNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioOrdenCedulacionEsigex
        {
            get
            {
                return this.IdFuncionarioOrdenCedulacionEsigexField;
            }
            set
            {
                this.IdFuncionarioOrdenCedulacionEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema
        {
            get
            {
                return this.IdTramiteNuevoSistemaField;
            }
            set
            {
                this.IdTramiteNuevoSistemaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteOrdenCedulacionEsigex
        {
            get
            {
                return this.IdTramiteOrdenCedulacionEsigexField;
            }
            set
            {
                this.IdTramiteOrdenCedulacionEsigexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs
        {
            get
            {
                return this.UsuarioWsField;
            }
            set
            {
                this.UsuarioWsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsuntosMigratoriosService.IServiceAsuntosMigratorios")]
    public interface IServiceAsuntosMigratorios
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisaResponse")]
        System.Threading.Tasks.Task<AsuntosMigratoriosService.GeneracionSolicitudMessage> GuardarSolicitudVisaAsync(AsuntosMigratoriosService.SolicitudInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisaResponse")]
        System.Threading.Tasks.Task<AsuntosMigratoriosService.GeneracionVisaMessage> GuardarVisaAsync(AsuntosMigratoriosService.VisaInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacionResponse")]
        System.Threading.Tasks.Task<AsuntosMigratoriosService.OrdenCedulacionMessage> GenerarOrdenCedulacionAsync(AsuntosMigratoriosService.OrdenCedulacionInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacionResponse")]
        System.Threading.Tasks.Task<AsuntosMigratoriosService.OrdenCedulacionMessage> ActualizarOrdenCedulacionAsync(AsuntosMigratoriosService.OrdenCedulacionV2Info datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceAsuntosMigratoriosChannel : AsuntosMigratoriosService.IServiceAsuntosMigratorios, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceAsuntosMigratoriosClient : System.ServiceModel.ClientBase<AsuntosMigratoriosService.IServiceAsuntosMigratorios>, AsuntosMigratoriosService.IServiceAsuntosMigratorios
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceAsuntosMigratoriosClient() : 
                base(ServiceAsuntosMigratoriosClient.GetDefaultBinding(), ServiceAsuntosMigratoriosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceAsuntosMigratorios.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAsuntosMigratoriosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceAsuntosMigratoriosClient.GetBindingForEndpoint(endpointConfiguration), ServiceAsuntosMigratoriosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAsuntosMigratoriosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceAsuntosMigratoriosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAsuntosMigratoriosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceAsuntosMigratoriosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceAsuntosMigratoriosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AsuntosMigratoriosService.GeneracionSolicitudMessage> GuardarSolicitudVisaAsync(AsuntosMigratoriosService.SolicitudInfo datos)
        {
            return base.Channel.GuardarSolicitudVisaAsync(datos);
        }
        
        public System.Threading.Tasks.Task<AsuntosMigratoriosService.GeneracionVisaMessage> GuardarVisaAsync(AsuntosMigratoriosService.VisaInfo datos)
        {
            return base.Channel.GuardarVisaAsync(datos);
        }
        
        public System.Threading.Tasks.Task<AsuntosMigratoriosService.OrdenCedulacionMessage> GenerarOrdenCedulacionAsync(AsuntosMigratoriosService.OrdenCedulacionInfo datos)
        {
            return base.Channel.GenerarOrdenCedulacionAsync(datos);
        }
        
        public System.Threading.Tasks.Task<AsuntosMigratoriosService.OrdenCedulacionMessage> ActualizarOrdenCedulacionAsync(AsuntosMigratoriosService.OrdenCedulacionV2Info datos)
        {
            return base.Channel.ActualizarOrdenCedulacionAsync(datos);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAsuntosMigratorios))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceAsuntosMigratorios))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.139.33/MREMH.ServiciosEsigexVisasRegularizacion.ServiceInterno/Ser" +
                        "viceAsuntosMigratorios.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceAsuntosMigratoriosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceAsuntosMigratorios);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceAsuntosMigratoriosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceAsuntosMigratorios);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceAsuntosMigratorios,
        }
    }
}
